[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/bcb/*"
  to = "https://api.bcb.gov.br/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
